config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server, at: '/cable'

  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
    scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, length: { minimum: 3, maximun: 15 },
    uniqueness: { case_sensitive: false }
    has_many :messages
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end 

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            # flash[:error] = "กรุณาเข้าสู่ระบบก่อน"
            redirect_to login_path
        end
    end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    #before_action :require_user

    def index
        @message = Message.new
        @messages = Message.custom_display
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user

    def create
        message = current_user.messages.build(message_params)
        if message.save
            # redirect_to root_path
            ActionCable.server.broadcast "chatroom_channel", mod_message: message_render(message)
        end 
    end 

    private 
    def message_params
        params.require(:message).permit(:body)
    end

    def message_render(message)
        render(partial: 'message', locals: {message: message})
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    before_action :logged_in_redirect, only: [:new, :create]

    def new
    end

    def create
        # byebug
        user = User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "ลงชื่อเข้าใช้สำเร็จ"
            redirect_to root_path
        else
            flash.now[:error] = "การลงชื่อเข้าใช้ผิดพลาดบางอย่าง"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "ออกจากระบบเรียบร้อยแล้ว"
        redirect_to login_path
    end

    private

    def logged_in_redirect
        if logged_in?
            flash[:error] = "คุณลงชื่ออยู่ในระบบอยู่แล้ว"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular users icon orange"></i>
  ห้องแชทชาวระยอง
</h2>

<div class="ui two column grid">
    <div class="twelve wide column">
        <div class="ui card fluid raised chatbox">
            <div class="content" id="messages">
                <div class="ui large feed" id="message-container" >
                    <%= render @messages%>
                </div>
            </div>
            <div class="extra content">

            <% if logged_in? %>
                <%= form_for(@message, html: {class: "ui reply form"}, role: "form", url: message_path, remote: true) do |f| %>
                    <div class="field" data-children-count="1">
                        <div class="ui fluid icon input">
                            <%= f.text_field :body %>
                            <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe  %>
                        </div>
                    </div>
                <% end %>   
            <% else %>
                <%= link_to '<div class="ui animated fade button fluid" tabindex="0">
                <div class="visible content">กรุณาลงชื่อเข้าใช้</div><div class="hidden content">เข้าใช้งานระบบ หรือ สมัครบัญชีใหม่</div>'.html_safe, login_path %>
                </div>
            <% end %>     
            </div>
        </div>
    </div>

    <div class="four wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content">
                <div class="ui vertical ">
                    <p>ปิด user online  ชั่วคราว...เพื่อประหยัด resource ของโฮส</p>
                    <p>ผู้ใหญ่ใจดีสามารถสนับสนุนค่าโฮสติ้งและระบบต่างๆ ได้ ติดต่อ 0928796292 หรือ samiti3d@gmail.com</p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
  <div class="ui inverted vertical footer segment" style="margin-top: 5em;">
    <div class="ui center aligned container">
      <div class="ui stackable inverted divided grid" style="padding-top: 2em;">
        <div class="three wide column">
          <h4 class="ui inverted header">ลิงก์เว็บไซต์เพื่อนบ้าน</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Link One</a>
            <a href="#" class="item">Link Two</a>
            <a href="#" class="item">Link Three</a>
            <a href="#" class="item">Link Four</a>
          </div>
        </div>
 
        <div class="seven wide column">
          <h4 class="ui inverted header">RayongBuddy.com คืออะไร</h4>
          <p>เป็นเว็บแอพฯ สำหรับการพบปะระหว่างบุคคลทั่วไป สำหรับการสนทนาผ่านระบบออนไลน์บน RayongBuddy.com และเป็นสื่อกลางช่วยเหลือ ให้คำแนะนำสังคมชาวจังหวัดระยอง เป้าหมายคือเทคโนโลยีเพื่อการพัฒนาสังคมไทย</p>
          <p>พัฒนาโดย สมิติ :)</p>

        </div>
      </div>
      <div class="ui inverted section divider"></div>
      <%# <img src="assets/images/logo.png" class="ui centered mini image"> %>
      <div class="ui horizontal inverted small divided link list">
        <a class="item" href="#">Site Map</a>
        <a class="item" href="#">Contact Us</a>
        <a class="item" href="#">Terms and Conditions</a>
        <a class="item" href="#">Privacy Policy</a>
      </div>
    </div>
  </div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
    <div class="ui message <%= message_type %>" transition >
        <i class="close icon"></i>
        <div class="header">
            <%= message_content %>
        </div>
        <p>เว็บไซต์นี้กำลังอยู่ในช่วงพัฒนา หากมีข้อสงสัยกรุณาติดต่อกระผม samiti3d@gmail.com</p>
    </div>    
<% end %>

app/views/layouts/_navigation.html.erb
  <div class="ui large menu">
    <div class="ui container">
      <%= link_to "<h3>RayongBuddy.com</h3>".html_safe, root_path, class: "item" %>
      <div class="right menu">
        <div class="ui dropdown item">
          บัญชี <i class="dropdown icon"></i>
          <div class="menu">
            <% if logged_in? %>
              <%= link_to "ออกจากระบบ", logout_path, method: :delete, class: "item" %>
            <% else %>
              <%= link_to "เข้าสู่ระบบ", login_path, class: "item" %>
            <% end %>
          </div>
        </div>
        <div class="item">
            <% if !logged_in? %>
              <%= link_to "ลงชื่อเข้าใช้", login_path, class: "item"%>
            <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>

    <%= favicon_link_tag %>
    <%= action_cable_meta_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
      <div class="ui container margin-top">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
        <div class="summary">
            <em><%= message.user.username %></em>: <%= message.body %>
        </div>
    </div>
</div>